"""empty message

Revision ID: 0dd0f30fda45
Revises: f7baf9f75ce4
Create Date: 2022-10-24 23:29:29.185171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd0f30fda45'
down_revision = 'f7baf9f75ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_user_id_fkey', 'team', type_='foreignkey')
    op.drop_constraint('team_pokemon_id_fkey', 'team', type_='foreignkey')
    op.drop_column('team', 'user_id')
    op.drop_column('team', 'id')
    op.drop_column('team', 'pokemon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('team', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('team', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('team_pokemon_id_fkey', 'team', 'pokemon', ['pokemon_id'], ['pokemon_id'])
    op.create_foreign_key('team_user_id_fkey', 'team', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
