"""empty message

Revision ID: 24b19f2bc4dd
Revises: b9c26b7065c0
Create Date: 2022-10-25 21:08:33.573967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b19f2bc4dd'
down_revision = 'b9c26b7065c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teamTable', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teamTable', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
