"""empty message

Revision ID: 6307c8ebe088
Revises: e7c90a453227
Create Date: 2022-10-24 22:44:03.768519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6307c8ebe088'
down_revision = 'e7c90a453227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_pokemon_join')
    op.create_unique_constraint(None, 'pokemon', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='unique')
    op.create_table('team_pokemon_join',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.pokemon_id'], name='team_pokemon_join_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name='team_pokemon_join_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_pokemon_join_pkey')
    )
    # ### end Alembic commands ###
