"""empty message

Revision ID: 7c27a7017b9f
Revises: 051bfe27515b
Create Date: 2022-10-26 21:59:18.131695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c27a7017b9f'
down_revision = '051bfe27515b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wins')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'ties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ties', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
