"""empty message

Revision ID: 850b02d29c7b
Revises: 92719c9be921
Create Date: 2022-10-26 21:56:56.722848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850b02d29c7b'
down_revision = '92719c9be921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'losses')
    op.drop_column('user', 'ties')
    op.drop_column('user', 'wins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ties', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
