"""empty message

Revision ID: b9c26b7065c0
Revises: 795b3a9cd159
Create Date: 2022-10-25 21:07:01.410593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c26b7065c0'
down_revision = '795b3a9cd159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teamTable', sa.Column('team_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teamTable', 'team_id')
    # ### end Alembic commands ###
