"""empty message

Revision ID: e7c90a453227
Revises: 4761c01dd6cb
Create Date: 2022-10-23 16:28:54.722037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c90a453227'
down_revision = '4761c01dd6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_pokemon_join', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('team_pokemon_join', sa.Column('pokemon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team_pokemon_join', 'team', ['team_id'], ['team_id'])
    op.create_foreign_key(None, 'team_pokemon_join', 'pokemon', ['pokemon_id'], ['pokemon_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_pokemon_join', type_='foreignkey')
    op.drop_constraint(None, 'team_pokemon_join', type_='foreignkey')
    op.drop_column('team_pokemon_join', 'pokemon_id')
    op.drop_column('team_pokemon_join', 'team_id')
    # ### end Alembic commands ###
