"""empty message

Revision ID: f7baf9f75ce4
Revises: 6307c8ebe088
Create Date: 2022-10-24 23:15:31.337125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7baf9f75ce4'
down_revision = '6307c8ebe088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('team', sa.Column('pokemon_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team', 'pokemon', ['pokemon_id'], ['pokemon_id'])
    op.drop_column('team', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'pokemon_id')
    op.drop_column('team', 'id')
    # ### end Alembic commands ###
