"""empty message

Revision ID: f82af73ec96a
Revises: a08f145320e6
Create Date: 2022-10-25 20:23:10.224363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82af73ec96a'
down_revision = 'a08f145320e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamTable',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.pokemon_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.pokemon_id'], name='team_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='team_user_id_fkey')
    )
    op.drop_table('teamTable')
    # ### end Alembic commands ###
